project_id = "xtqbrljcztkjwdhgrhly"

[functions.leads-submit]
verify_jwt = false

[functions.receive-leads]
verify_jwt = false

[functions.create-meet-event]
verify_jwt = false

[functions.send-event-invite]
verify_jwt = false
